version: '3.6'
services:
  telegraf:
    image: telegraf:1.18-alpine
    platform: linux/x86_64
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
      - php
      - nginx
    hostname: b-telegraf
    ports:
      - '127.0.0.1:8125:8125/udp'

  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: socket-proxy
    restart: always
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '127.0.0.1:2375:2375'
    environment:
      - LOG_LEVEL=debug
      - CONTAINERS=1
      - INFO=1

  influxdb:
    image: influxdb:1.8-alpine
    platform: linux/x86_64
    env_file: configuration.env
    hostname: b-influxdb
    ports:
      - '127.0.0.1:8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:8.0.2
    platform: linux/x86_64
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    hostname: b-grafana
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

  php:
    image: php:7.4-fpm
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf

  nginx:
    image: nginx:latest
    volumes:
      - ./src:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    links:
      - php
    ports:
      - '127.0.0.1:8080:80'

volumes:
  grafana_data: {}
  influxdb_data: {}
